---
title: "Task 7"
author: "Brink"
date: "9/19/2022"
output: 
  html_document:
    keep_md: TRUE
    code_folding: 'hide'
---
install.packages("lubridate")
install.packages("ggrepel")

```{r}
library(tidyverse)
library(lubridate)
library(ggrepel)
library(ggplot2)
library(readr)
library(knitr)
library(dplyr)
library(forcats)
library(downloader)
```
```{r}
download.file("https://raw.githubusercontent.com/hadley/r4ds/master/data/heights.csv", "heights")
```
```{r}
Height <- read_csv("heights")
Height
```

```{r}
HeightEd <- Height %>%
  mutate(ed = as.factor(ed)) %>%
  mutate(ed = fct_recode(ed,
                         "primary" = "3",
                         "primary" = "4",
                         "primary" = "5",
                         "primary" = "6",
                         "secondary" = "7",
                         "secondary" = "8",
                         "secondary" = "9",
                         "secondary" = "10",
                         "secondary" = "11",
                         "highschoolgrad" = "12",
                         "associates" = "13",
                         "associates" = "14",
                         "associates" = "15",
                         "bachelors" =  "16",
                         "mastersdoctorate" = "17",
                         "mastersdoctorate" = "18"))
```

```{r}
HeightEd1 <- HeightEd %>%
  group_by(race) %>%
  count(ed)
HeightEd1
```
```{r}
ggplot(HeightEd1, mapping = aes(ed,n, fill=race))+
  geom_bar(stat="identity", position="dodge")
```
```{r}
HeightEd2 <- HeightEd %>%
  group_by(sex) %>%
  count(ed)
HeightEd2
```
```{r}
ggplot(HeightEd2, mapping = aes(ed,n, fill=sex))+
  geom_bar(stat="identity", position="dodge")
```
```{r}
HeightEd3 <- HeightEd %>%
  group_by(earn) %>%
  count(ed)
HeightEd3
```
```{r}
ggplot(HeightEd3, mapping = aes(ed,n, fill=earn))+
  geom_bar(stat="identity", position="dodge")+
  labs(y = "Annual Earnings", x = "Type of Education", title = "Annual Earnings", subtitle = 'Part 3 of Task') 
```
```{r Answer to personal graph}
#To construct this graph, I took the same formula that we had used for the previous comparisons between education and sex/race in that I made a tibble grouping the data together, except wanted to compare education and annual earnings. I could've added elements to increase the detail of the graph, but I believe the message of it is still clear, those with a masters degree or a bachelor's degree than those with less than, being either a high school diploma or an associates. 
```

