---
title: "Case Study 6"
author: "Brink"
date: "10/3/2022"
output: 
  html_document:
    theme: united
    keep_md: True
    code_folding: 'hide'
---
```{r}
library(tidyverse)
library(gridExtra)
```

```{r}
?diamonds
head(diamonds)
str(diamonds)
```

```{r}
ggplot(diamonds, aes(x)) +
  geom_histogram(color = 'black', fill = 'blue') +
  labs(x = 'Length (mm)', y = 'Occurances', title = 'Varying Diamond Lengths') +
  coord_cartesian(xlim = c(3,10),ylim = c(0, 10000), expand = FALSE) +
  theme_bw()
```

```{r}
ggplot(diamonds, aes(y)) +
  geom_histogram(color = 'black', fill = 'snow2', binwidth = .20) +
  labs(x = 'Width (mm)', y = 'Occurances', title = 'Varying Diamond Widths') +
  coord_cartesian(xlim = c(3,10), ylim = c(0, 7000), expand = FALSE) +
  theme_bw()
```

```{r}
ggplot(diamonds, aes(z)) +
  geom_histogram(color = 'black', fill = 'blue', binwidth = .3) +
  labs(x = 'Depth (mm)', y = 'Occurances', title = 'Varying Diamond Depths') +
  coord_cartesian(xlim = c(2,6), ylim = c(0, 7500), expand = FALSE) +
  theme_bw()
```

```{r}
ggplot(diamonds, aes(price)) +
  geom_histogram(color = 'black', fill = 'blue') +
  labs(x = 'Price in Dollars', y = 'Occurances', title = 'Varying Diamond Price') +
  theme_bw()
```
Distribution looks to be right skewed with most diamonds being less than $5000

```{r}
ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth() +
  labs(x = 'Carat', y = 'Price in Dollars', title = 'Price vs. Carat') +
  coord_cartesian(ylim = c(0, 20000), expand = TRUE) +
  theme_bw()
```

```{r}
ggplot(diamonds, aes(cut, carat)) +
  geom_boxplot(aes(fill = cut), color = 'blue') +
  labs(x = 'Cut', y = 'Carat', title = 'Diamond Cut vs. Carat') +
  theme_bw()
```
There are less carots in higher cut diamonds

```{r}
ggplot(data = diamonds, aes(x = carat, y = price)) + 
  geom_point(aes(color = clarity), alpha = 1) +
  geom_smooth()+
  scale_y_continuous(limits = c(350, 15000),
    breaks = c(300, 1500, 6000, 12000, 15000)) +
  coord_cartesian(xlim = c(0, 4), ylim = c(0,16000), expand = FALSE) +
  labs(x = 'Carat', y = 'Price in Dollars', title = 'Carat vs. Price') +
  theme_bw()
```
More carots equal a higher price, but that does not parallel with quality

```{r}
diamonds %>%
  mutate(price_part =
           case_when(
             price >= 0 & price <= 2500 ~ '0-2500',
             price >= 2501 & price <= 5000 ~ '2501-5000',
             price >= 5001 & price <= 7500 ~ '5001-7501',
             price >= 7501 & price <= 10000 ~ '7501-10000',
             price >= 10001 & price <= 12500 ~ '10001-12500',
             price >= 12501 & price <= 15000 ~ '12501-15000',
             price >= 15001 & price <= 17500 ~ '15001-17500',
             price >= 17501 & price <= 20000 ~ '17501-20000',
             price >= 20001 & price <= 22500 ~ '20001-22500',
             price >= 22501 & price <= 25000 ~ '22501-25000'),
         price_part =  fct_relevel(price_part,'0-3000','2501-5000','5001-7501','7501-10000','10001-12500','12501-15000','15001-17500','17501-20000','20001-22500','22501-25000')) %>%
  ggplot(aes(carat, price, fill = price_part)) +
    geom_boxplot() +
    scale_fill_brewer(palette = 'Reds') +
    labs(x = 'Carat', y = 'Price ($USD)', title = 'Carat grouped by Price', fill = "Price Ranges") +
    theme_bw()
```

```{r}
Large <- diamonds %>%
  filter(carat >= 4) %>%
  ggplot(aes(price)) +
    geom_histogram(color = 'black', fill = 'blue') +
    labs(x = 'Price in Dollars', y = 'Occurances', title = 'Large Diamond Price Distribution', subtitle = 'Carat >= 4') +
    theme_bw()
```

```{r}
Small <- diamonds %>%
  filter(carat <= 1) %>%
  ggplot(aes(price)) +
    geom_histogram(color = 'black', fill = 'red') +
    labs(x = 'Price in Dollars', y = 'Occurances', title = 'Small Diamond Price Distribution', subtitle = 'Carat <= 1') +
    theme_bw()

grid.arrange(Large, Small, nrow = 2)
```
While predictable, the graphs prove that large diamonds, that being with 4 carats or more, are going to be more expensive on average than smaller diamonds. 

```{r}
ggplot(diamonds, aes(x = carat, y = price, fill = cut)) +
    geom_col(alpha = 1) +
    coord_cartesian(xlim = c(0,4), ylim = c(0, 2500000), expand = FALSE) +
    facet_wrap(~cut, scales = 'free') +
    labs(x = 'Carat', y = 'Price in Dollars', title = 'Relationship between Carat and Price with respect to Cut Type') +
    theme_bw() 
```

