---
title: "Case 11"
author: "Brink"
date: "11/14/2022"
output: 
  html_document:
    keep_md: TRUE
---

```{r}
library(ggplot2)
library(readr)
library(knitr)
library(dplyr)
library(forcats)
library(downloader)
library(corrplot)
library(tidyquant)
library(timetk)
library(dygraphs)
library(scales)
library(tidyverse)
library(sf)
library(USAboundaries)
library(maps)
library(ggsflabel)
library(devtools)
library(remotes)
library(stringr)
library(leaflet)
library(mapview)
```

```{r}
permit_data <- tempfile()
download("https://raw.githubusercontent.com/WJC-Data-Science/DTS350/master/permits.csv", 
         permit_data, mode = "wb")
permits <- read_csv(permit_data)
```
```{r}
permits1 <- permits %>%
  filter(StateAbbr == "PA", year==2010)
```


```{r}
penn <- read.csv('pennlatlong.csv')
head(penn)
```
```{r}
penn1 <- penn %>%
  mutate(county = as.character(County.Code.Number))
```

```{r}
permits2 <- permits1 %>%
  mutate(county = as.character(county))
```

```{r}
both <- left_join(penn1,permits2, by='county')
head(both)
```
```{r}
both1 <- both %>%
  arrange(desc(value))
```


```{r}
both1$quartile <- ntile(both$value,4)
both1$quartile
```

```{r}
bestcounty <- both1 %>%
  filter(row_number() == 1)
```


```{r}
PA <- us_counties(state = 'PA')
```

```{r}
PAcounties <- ggplot(PA) +
  geom_sf()
PAcounties
```
```{r}
ntile4 <- both1 %>%
  filter(quartile == 4)

ntile3 <- both1 %>%
  filter(quartile == 3)

ntile2 <- both1 %>%
  filter(quartile == 2)

ntile1 <- both1 %>%
  filter(quartile == 1)
```


```{r}
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = ntile4,
                   radius = 7,
                   color = "blue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~county,
                   label = ~value) %>%
    addCircleMarkers(data = ntile3,
                   radius = 7,
                   color = "red",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~county,
                   label = ~value)%>%
    addCircleMarkers(data = ntile2,
                   radius = 7,
                   color = "darkblue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~county,
                   label = ~value) %>%
    addCircleMarkers(data = ntile1,
                   radius = 7,
                   color = "green",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~county,
                   label = ~value) %>%
    addCircleMarkers(data = bestcounty,
                   radius = 7,
                   color = "royalblue1",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~county,
                   label = ~value)
```

In my leaflet visualization, I was able to specifically designate each ntile with a unique color, in addition to the county with the most amount of permits. I'm not confident that the data is joined together correctly, due to some columns not matching each other correctly.

